allprojects {
    repositories {
        google()
        mavenCentral()
        // Official MuPDF / Artifex Maven (fitz JNI)
        maven { url 'https://maven.ghostscript.com/' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
